config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('frontend.urls')),
    path('orders/', include('orders.urls')),
    path('api/', include('books.api.urls', namespace='api')),
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
]

mercantile/books/api/urls.py
from django.urls import path
from . import views

app_name = 'books'
urlpatterns = [
    path('books/', views.BookListView.as_view(), name='book_list'),
    path('books/<pk>/', views.BookDetailView.as_view(), name='book_detail'),
    path('book/', views.BookCreateView.as_view(), name='book_create'),
]

mercantile/books/urls.py
from django.urls import path
from . import views

app_name = 'books'
urlpatterns = [
]

mercantile/frontend/urls.py
from django.urls import path

from frontend.views import FrontEndView

app_name = 'frontend'
urlpatterns = [
    path('', FrontEndView.as_view(), name='index'),
]

mercantile/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('', views.orders, name='list'),
    path('<int:order_id>/', views.order, name='detail'),
]

mercantile/books/models.py
from django.db import models


class Book(models.Model):
    id = models.CharField(max_length=255, primary_key=True)
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255)

    class Meta:
        ordering = ['author', 'title']

    def __str__(self):
        return self.title

mercantile/orders/models.py
from django.db import models


class Order(models.Model):
    date_ordered = models.DateTimeField(auto_now_add=True)
    date_shipped = models.DateTimeField(blank=True, null=True)

    class Meta:
        ordering = ('-date_ordered',)

    def __str__(self):
        return f'#{self.id} {self.date_ordered.strftime("%d/%m/%Y %H:%M")}'


class OrderLine(models.Model):
    order = models.ForeignKey('Order', on_delete=models.CASCADE)
    book_id = models.CharField(max_length=20)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return self.book_id

mercantile/books/api/views.py
from rest_framework import generics

from .serializers import BookSerializer
from ..models import Book


class BookListView(generics.ListAPIView):
    queryset = Book.objects.all()
    serializer_class = BookSerializer


class BookDetailView(generics.RetrieveAPIView):
    queryset = Book.objects.all()
    serializer_class = BookSerializer


class BookCreateView(generics.ListCreateAPIView):
    queryset = Book.objects.all()
    serializer_class = BookSerializer

mercantile/frontend/views.py
from django.views.generic import TemplateView


class FrontEndView(TemplateView):
    template_name = 'home.html'

mercantile/orders/views.py
from django.http import HttpResponse


def orders(request):
    return HttpResponse(f'Order list goes here')


def order(request, order_id):
    return HttpResponse(f'Order {order_id} goes here')

mercantile/templates/base.html
<!DOCTYPE html>
<html lang="en" >

{% load static %}

<head >
  <meta charset="utf-8" >
  <meta name="viewport" content="width=device-width, initial-scale=1" >

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous" >
  <link rel="stylesheet" type="text/css" href="{% static 'mercantile/css/base.css' %}" >
  {% block stylesheets %}{% endblock stylesheets %}
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300" rel="stylesheet" >


  <title >{% block title %}{% endblock title %}</title >
  <link rel="shortcut icon" type="image/svg+xml" href="{% static 'mercantile/icons/favicon.svg' %}" />
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'mercantile/icons/favicon-32x32.png' %}" >
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'mercantile/icons/favicon-16x16.png' %}" >
  <link rel="shortcut icon" href="{% static 'mercantile/icons/favicon.ico' %}" >
</head >
<body >

<div id="content" >
  {% block content %}{% endblock content %}
</div >

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous" >
</script >
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous" >
</script >
<script >window.static = {% static '' %}</script >
<script src="{% static 'mercantile/js/main.js' %}" ></script >
<noscript>Please enable JavaScript to view this site.</noscript>
</body >
</html >

mercantile/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Mercantile {% block subtitle %}{% endblock subtitle %}
{% endblock title %}

{% block stylesheets %}
  <link rel="stylesheet"
        href="{% static 'mercantile/css/social-circles.css' %}" >
{% endblock stylesheets %}

{% block content %}
  <script >window.url = "{% url 'frontend:index' %}"</script >
  <nav id="navbar-root" class="navbar navbar-dark navbar-expand-lg px-4 px-lg-5 py-3 bg-color-dark" ></nav >

  <div id="react-root"></div>

  <div id="footer-root"></div>

  <section id="footer" class="bg-color-dark" >
    <div class="container-fluid px-4 px-lg-5" >
      <div class="row py-3 align-items-center" >
        <div class="col-8 col-md-10" >
          <div class="d-flex flex-column flex-md-row" >
            <div class="pr-lg-2" >
              <a href="https://behind-the-web.herokuapp.com/" >Crafted by Kate</a >
            </div >
            <div class="d-none d-md-inline" >&bull;</div >
            <div class="pl-lg-2" >Powered by Django</div >
          </div >
        </div >
        <div class="col-4 col-md-2 px-0" >
          <div class="d-flex justify-content-end" >
            <div class="pr-2 pr-lg-3" >
              <a class="icon-linkedin social-button borderless"
                 href="https://www.linkedin.com/in/katemckenzie/" >
              </a >
            </div >
            <div class="pr-4" >
              <a class="icon-github social-button borderless"
                 href="https://github.com/katemakescode/mercantile" >
              </a >
            </div >
          </div >
        </div >
      </div >
    </div >
  </section >
{% endblock content %}

mercantile/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Mercantile {% block subtitle %}{% endblock subtitle %}
{% endblock title %}

{% block stylesheets %}
    <link rel="stylesheet"
          href="{% static 'mercantile/css/social-circles.css' %}">
{% endblock stylesheets %}

{% block content %}
    <nav class="navbar navbar-dark navbar-expand-lg px-4 px-lg-5 py-3 bg-color-dark">
        <a href="{% url 'home:index' %}" class="navbar-brand">
            Mercantile
        </a>
        <button class="navbar-toggler" data-toggle="collapse"
                data-target="#navbar-menu">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div id="navbar-menu" class="collapse navbar-collapse">
            <ul class="navbar-nav ms-auto">
                <li class="navbar-item">
                    <a href="#projects" class="nav-link">Wishlist</a>
                </li>
                <li class="navbar-item">
                    <a href="#about" class="nav-link">Cart</a>
                </li>
            </ul>
        </div>
    </nav>

    <section id="masthead" class="bg-color-light">
        <div class="container pt-4 py-lg-5">
            <div class="row d-flex py-4 justify-content-center">
                <div class="col-6 col-lg-12 d-flex justify-content-center">
                    <img class="img-fluid"
                         alt="Cobweb by prettycons on www.flaticon.com"
                         src="{% static 'mercantile/img/cobweb-warm.png' %}">
                </div>

            </div>
            <div class="d-flex pt-3 justify-content-center">
                <h2 class="banner">MERCANTILE</h2>
            </div>
            <div class="d-flex pt-0 pt-lg-3 pb-5 justify-content-center">
                <h5 class="subbanner">Books for Book Lovers</h5>
            </div>
        </div>
    </section>

    <section id="projects" class="">
        <div class="container py-5">
            <div class="d-flex justify-content-center">
                <h3>BESTSELLERS</h3>
            </div>
            <div class="row d-flex justify-content-center">
                <div class="card col-md-2 mx-4 mx-md-4 my-4 pt-3">
                    <a href="{{ overtrick_url }}">
                        <div class="card-body m-2">
                            <img class="card-img-top"
                                 alt="Cover of the 2000 Modern Library edition of Anna Karenina by Leo Tolstoy"
                                 src="{% static 'mercantile/img/anna_karenina.jpeg' %}">
                            <h5 class="card-title pt-3">
                                Anna Karenina
                            </h5>
                            <p class="card-text">Leo Tolstoy</p>
                        </div>
                    </a>
                </div>
                <div class="card col-md-2 mx-4 mx-md-4 my-4 pt-3">
                    <a href="{{ overtrick_url }}">
                        <div class="card-body m-2">
                            <img class="card-img-top"
                                 alt="Cover of the 2000 Modern Library edition of Anna Karenina by Leo Tolstoy"
                                 src="{% static 'mercantile/img/anna_karenina.jpeg' %}">
                            <h5 class="card-title pt-3">
                                Anna Karenina
                            </h5>
                            <p class="card-text">Leo Tolstoy</p>
                        </div>
                    </a>
                </div>
                <div class="card col-md-2 mx-4 mx-md-4 my-4 pt-3">
                    <a href="{{ overtrick_url }}">
                        <div class="card-body m-2">
                            <img class="card-img-top"
                                 alt="Cover of the 2000 Modern Library edition of Anna Karenina by Leo Tolstoy"
                                 src="{% static 'mercantile/img/anna_karenina.jpeg' %}">
                            <h5 class="card-title pt-3">
                                Anna Karenina
                            </h5>
                            <p class="card-text">Leo Tolstoy</p>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>

    <section id="about" class="py-5 bg-color-light text-center">
        <div class="container d-flex py-5 justify-content-center">
            <div class="col col-md-9 mx-auto">
                <h3>WARNING</h3>
                <h5 class="text my-4 px-1">
                    This bookstore, despite appearances, sells no books.
                </h5>
                <button id="click" class="btn btn-outline mt-4">Clickety</button>
            </div>
        </div>
    </section>

    <section id="footer" class="bg-color-dark">
        <div class="container-fluid px-4 px-lg-5">
            <div class="row py-3 align-items-center">
                <div class="col-8 col-md-10">
                    <div class="d-flex flex-column flex-md-row">
                        <div class="pe-lg-2">Crafted by Kate</div>
                        <div class="d-none d-md-inline">&bull;</div>
                        <div class="ps-lg-2">Powered by Django</div>
                    </div>
                </div>
                <div class="col-4 col-md-2 px-0">
                    <div class="d-flex justify-content-end">
                        <div class="pe-2 pe-lg-3">
                            <a class="icon-linkedin social-button borderless"
                               href="https://www.linkedin.com/in/katemckenzie/">
                            </a>
                        </div>
                        <div class="pe-4">
                            <a class="icon-github social-button borderless"
                               href="https://github.com/katemakescode/behind-the-web">
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}